### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by moorepatrick**
This is an on-topic initial pull request template

### CODE REVIEW

**Comment by HakyungKwon-TRI** [comment]
Looks like it doesn't like that the coverage has decreased?

**Comment by moorepatrick** [comment]
Let me see if I can have pytest ignore those files.

**Comment by moorepatrick** [comment]
I didn't look far enough into the coveralls report. None of the monitored files changed, so coverage should not have decreased. I think it's probably just a rounding/precision issue with Coveralls. I think it would be inappropriate to add additional changes to this PR to make that check pass.

**Comment by JosephMontoya-TRI** [comment]
Yeah, something to do with AWS secrets exception getting uncovered, but definitely doesn't matter

**Pull request merged**
