### PR TITLE
Update docs with tutorial on new structuring

### PR DESCRIPTION
**Pull request by ardunn**
This new documentation page should help both devs and users understand the new structuring syntax.

Here's a screenshot of the beginning of this page:
Screen Shot 2021-03-24 at 7 56 51 PM

Note that the documentation test will fail until #150 is merged.

### CODE REVIEW

**Comment by ardunn** [comment]
closes #117

**Review by patrickherring-TRI — COMMENTED** [review]
Looks like it cannot find one of the files for the tutorial: `FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beep/beep/beep/tests/../../docs_src/tutorial.md'`

**Comment by ardunn** [comment]
@patrickherring-TRI fixed

**Comment by ardunn** [comment]
@patrickherring-TRI should be fixed now, only failing check is coveralls which is somewhat perplexing as the same amount of code is tested...?

**Review by patrickherring-TRI — APPROVED** [review]
LGTM!

**Pull request merged**
