### PR TITLE
New Diagnostic Structure and Interpolation

### PR DESCRIPTION
**Pull request by ardunn**
# summary:
- introduces a new class, `DiagnosticConfigBasic`, which records where in a given dataframe diagnostic cycles are.
- This new class is used to more flexibly interpolate diagnostic cycles

# todo
- [X] add new class, `DiagnosticConfig`, to support the identification of various diagnostic cycles (including user-defined, nonRPT nonHPPC)
    - [X] tests for `DiagnosticConfig`
- [X] update base class to support interpolation and allow for serialization
    - [X] change tests and existing cycler code to support new class
- [X] change regular interpolation cycles to interpolate based on step (giving same num. points per step rather than same num. points per cycle)
    - [X] update tests
- [X] Fix classification of regular charge/discharge cycles by removing "spurious" points if present; still works with hold steps but does not interpolate single point steps
    - Adds an attribute `indeterminate_step_default_charge` which can be set after Datapath instantiation; True means indeterminate steps are classified as charge steps, False means indeterminate steps are classified as discharge steps.
- [X] disable CLI tests for time being
- [X] remove `BEEPDatapath` `autostructure` and `determine_structuring_parameters`
- [X] move parameters lookup code to deprecated module
- [X] rename Novonix conversion `step_type_num` --> `step_index` for more standardization, as `step_index` is now the canonical name for integer/categories denoting step types. also rename the Novonix step number, previously known confusingly as `step_index`, to `step_num`. 
- [X] Remove need for Novonix to override base method for iterating through steps.

### CODE REVIEW

**Comment by ardunn** [comment]
> Is there information or documentation about what exactly a diagnostic cycle is, or the different types?

Not yet in the documentation. There will be soon.

In essence, diagnostic is just a term we use for describing custom cycles and dealing with them with more granular control. We consider RPT and HPPC cycles as diagnostic. For some cyclers, we will consider other cycle types to be diagnostic (e.g., some Maccor cyclers with RESET cycles) as well as let people define their own diagnostic cycle types with their own characteristics. 

I am open to revising this definition

**Comment by ardunn** [comment]
# Example usage `2022.01.14`


```python
from beep.structure.maccor import MaccorDatapath
from beep.structure.diagnostic import DiagnosticConfig

md = MaccorDatapath.from_file("Nova_Regular_115.maccor.rar")


# STEP 1: Configure a diagnostic using automatic step number recognition
dc = DiagnosticConfig.from_step_numbers(
        md.raw_data,
        matching_criteria={
            "hppc": ("contains", [(1, 2, 4, 6, 8)]),
            "rpt_lowrate": ("exact", [(12, 13)]),
            "rpt_highrate": ("exact", [(15, 16)])
        }
    )

# Note: you can equivalently have just manually specified the step numbers and passed it into __init__, like this:
# dc = DiagnosticConfig({"hppc": [0,8,24,127], "rpt_lowrate": [1,25,128], "rpt_highrate": [2,26,129]})


# STEP 2: Set the diagnostic attribute of the datapath!
md.diagnostic = dc

# STEP 3: Interpolate
# automatically runs diagnostic and regular structuring + summaries with default params
# if you want to specify custom structuring parameters, call the individual interpolate_diagnostic, interpolate_cycles, summarize_diagnostic, and summarize_cycles with your own parameters
md.structure()    
```

Out:
```
Interpolating diagnostic by step:   3%|▎         | 4/156 [00:00<00:04, 37.56it/s]2023-01-14 15:18:16 DEBUG    Step number 2 with step type 2 has less than 2 interpolated points; refusing to append to interpolated data.
Interpolating diagnostic by step:  26%|██▋       | 41/156 [00:00<00:01, 65.51it/s]2023-01-14 15:18:16 DEBUG    Skipping cycle: 8, step: 1 with step type: 5 as there were < 2 data points.
2023-01-14 15:18:16 DEBUG    Step number 1 with step type 5 has less than 2 interpolated points; refusing to append to interpolated data.
Interpolating diagnostic by step:  46%|████▌     | 71/156 [00:01<00:01, 66.49it/s]2023-01-14 15:18:17 DEBUG    Step number 4 with step type 10 has less than 2 interpolated points; refusing to append to interpolated data.
Interpolating diagnostic by step:  51%|█████     | 79/156 [00:01<00:01, 68.30it/s]2023-01-14 15:18:17 DEBUG    Skipping cycle: 24, step: 1 with step type: 5 as there were < 2 data points.
2023-01-14 15:18:17 DEBUG    Step number 1 with step type 5 has less than 2 interpolated points; refusing to append to interpolated data.
Interpolating diagnostic by step:  69%|██████▉   | 108/156 [00:01<00:00, 63.37it/s]2023-01-14 15:18:17 DEBUG    Step number 4 with step type 19 has less than 2 interpolated points; refusing to append to interpolated data.
Interpolating diagnostic by step:  78%|███████▊  | 122/156 [00:01<00:00, 64.30it/s]2023-01-14 15:18:18 DEBUG    Skipping cycle: 127, step: 1 with step type: 5 as there were < 2 data points.
2023-01-14 15:18:18 DEBUG    Step number 1 with step type 5 has less than 2 interpolated points; refusing to append to interpolated data.
Interpolating diagnostic by step:  96%|█████████▌| 150/156 [00:02<00:00, 59.43it/s]2023-01-14 15:18:18 DEBUG    Step number 4 with step type 19 has less than 2 interpolated points; refusing to append to interpolated data.
Interpolating diagnostic by step: 100%|██████████| 156/156 [00:02<00:00, 61.89it/s]
Interpolating discharge (2.8 - 3.5)V (1000 points): 100%|██████████| 120/120 [00:02<00:00, 42.94it/s]
Interpolating charge on axis charge_capacity (1000 points): 100%|██████████| 120/120 [00:03<00:00, 32.11it/s]
```


Now you can access individual parts of the diagnostic config and diagnostic interpolated data pretty easily!

# Get the cycle indices of the rpt lowrate cycles using the label you defined in the DiagnosticConfig
```python
md.diagnostic.cycles["rpt_lowrate"]
```

```
frozenset({1, 25, 128})
```

### Get the cycle indices of ALL rpt cycles together
```python
md.diagnostic.rpt_ix
```

```
Out[24]: frozenset({1, 2, 25, 26, 128})
```

### Get the interpolated diagnostic cycles for the "rpt_highrate" steps

```
diag_data = md.diagnostic_data
diag_data[diag_data["cycle_type"] == "rpt_highrate"]
df = md.diagnostic_data
```

```
Out[23]: 
           test_time   current   voltage  internal_resistance  charge_capacity  discharge_capacity  charge_energy  discharge_energy  temperature  cycle_index    cycle_type  step_index  step_index_counter step_type  discharge_dQdV  charge_dQdV
18000  179035.200000  0.048707  3.028534                  0.0     6.166000e-07            0.000000       0.000002          0.000000          NaN            2  rpt_highrate          15                   1         0             NaN          NaN
18001  179035.229712  0.048575  3.031283                  0.0     1.014149e-06            0.000000       0.000003          0.000000          NaN            2  rpt_highrate          15                   1         0        0.000000     0.000145
18002  179035.259424  0.048443  3.034032                  0.0     1.411698e-06            0.000000       0.000004          0.000000          NaN            2  rpt_highrate          15                   1         0        0.000000     0.000145
18003  179035.289137  0.048312  3.036780                  0.0     1.809247e-06            0.000000       0.000005          0.000000          NaN            2  rpt_highrate          15                   1         0        0.000000     0.000145
18004  179035.318849  0.048180  3.039529                  0.0     2.206796e-06            0.000000       0.000007          0.000000          NaN            2  rpt_highrate          15                   1         0        0.000000     0.000145
              ...       ...       ...                  ...              ...                 ...            ...               ...          ...          ...           ...         ...                 ...       ...             ...          ...
55504  703522.007335 -0.047997  3.011089                  0.0     2.652191e-01            0.258505       1.013146          0.973019          NaN           26  rpt_highrate          16                   2         1       -0.013690     0.000000
55503  703524.854365 -0.047997  3.008317                  0.0     2.652191e-01            0.258543       1.013146          0.973133          NaN           26  rpt_highrate          16                   2         1       -0.013553     0.000000
55502  703527.672942 -0.047997  3.005544                  0.0     2.652191e-01            0.258581       1.013146          0.973246          NaN           26  rpt_highrate          16                   2         1       -0.013508     0.000000
55501  703530.482143 -0.047997  3.002772                  0.0     2.652191e-01            0.258618       1.013146          0.973359          NaN           26  rpt_highrate          16                   2         1       -0.012829     0.000000
55500  703533.150000 -0.048020  3.000000                  0.0     2.652191e-01            0.258654       1.013146          0.973465          NaN           26  rpt_highrate          16                   2         1             NaN          NaN
[2000 rows x 16 columns]
```


### Get the diagnostic summary
```
md.diagnostic_summary
```

```
Out[17]: 
   cycle_index  discharge_capacity  charge_capacity  discharge_energy  charge_energy  temperature_maximum  temperature_average  temperature_minimum              date_time_iso  coulombic_efficiency  paused    cycle_type     CV_time  CV_current  CV_capacity
0            0            0.273355         0.271208          1.016899       1.041215                  NaN                  NaN                  NaN  2022-09-20T19:14:33+00:00              1.007915       0          hppc   10.000000    0.000000     0.000000
1            1            0.270688         0.268340          1.019012       1.026203                  NaN                  NaN                  NaN  2022-09-21T16:43:44+00:00              1.008750       0   rpt_lowrate  522.890015    0.011994     0.003576
2            2            0.261415         0.269480          0.983684       1.029480                  NaN                  NaN                  NaN  2022-09-22T20:58:37+00:00              0.970072       0  rpt_highrate  491.290009    0.011994     0.003342
3            8            0.271856         0.252745          1.014022       0.973805                  NaN                  NaN                  NaN  2022-09-23T21:40:43+00:00              1.075613       0          hppc   10.000000    0.000000     0.000000
4           24            0.269405         0.252612          1.006470       0.972771                  NaN                  NaN                  NaN  2022-09-26T11:04:10+00:00              1.066475       0          hppc   10.000000    0.000000     0.000000
5           25            0.266823         0.262944          1.005619       1.005288                  NaN                  NaN                  NaN  2022-09-27T07:54:17+00:00              1.014753       0   rpt_lowrate  459.829987    0.011994     0.003167
6           26            0.258654         0.265219          0.973465       1.013146                  NaN                  NaN                  NaN  2022-09-28T11:42:33+00:00              0.975245   41494  rpt_highrate  459.609985    0.011994     0.003219
7          127            0.261073         0.249938          0.978333       0.961707                  NaN                  NaN                  NaN  2022-10-10T13:34:05+00:00              1.044553       0          hppc   10.000000    0.000000     0.000000
8          128            0.094658         0.254381          0.387571       0.974060                  NaN                  NaN                  NaN  2022-10-11T10:09:27+00:00              0.372110       0   rpt_lowrate  470.260010    0.011994     0.003257

```



### Write the entire datapath (including diagnostic, interpolated diagnostic data, and interpolated regular data) to a file

```python
md.to_json_file("maccor.json")
```

### Read the entire datapath back from that file
```python
md = MaccorDatapath.from_json_file("maccor.json")
```


NOTE: You can use whatever labels you want in the `DiagnosticConfig` as long as the string `rpt` is somwhere in the name for RPT cycles, `hppc` is somewhere in the name for HPPC cycles, and `reset` is somewhere in the name for Reset cycles. It is entirely user-configurable.

**Comment by shijingsun-TRI** [comment]
@ardunn  a quick question - how to best set up interpolation for customized diagnostic cycle_types (rather than hppc or rpt)?

**Comment by ardunn** [comment]
@shijingsun-TRI this is ready to merge

**Comment by ardunn** [comment]
Added documentation as well under Python Tutorials -> Advanced Structuring: Diagnostic and Custom Cycles

Preview


image

image

image

**Review by shijingsun-TRI — APPROVED** [review]
LGTM

**Pull request merged**
